### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by quasipedia** [Elinvention/gnome-shell-extension-nasa-apod#1]
Does not work on Gnome version 3.22.2 (Fedora 25).
Only the default background colour is displayed.
The "show description" and "refresh" options are also always greyed out.
Cool idea though! :)

**Comment by Elinvention** [comment]
I think it should work now. Let me know. Thanks!

**Comment by quasipedia** [comment]
I think it will take a few days for the updated version to be on https://extensions.gnome.org... but I'll let you know then! :)

**Comment by quasipedia** [comment]
Nice.  It works now! 👍 
Thanks again! 😄
