### ISSUE TITLE
Stop working on Fedora

### ISSUE THREAD

**Issue by quasipedia** [Elinvention/gnome-shell-extension-nasa-apod#10]
After the last update from extensions.gnome.org the extension stopped working.

The screen is blue (as in: no picture displayed) and the "NASA APOD website" button at the bottom of the notification does not work.  However the picture is present in the settings -> cache panel and the description is shown correctly.

I run Fedora workstation 26, 64bit, fully upgraded.

=======

Live update! 🙂

While I was writing this, the notification popped up that an update of the extension was available.  The update fixes the background image, but **the button is still broken**.

**Comment by Elinvention** [comment]
Yes, I didn't notice this error because of cut and paste and lack of warnings by the interpreter. I will release a new version soon.

Thanks.
