### ISSUE TITLE
[enhancement] Picture-options

### ISSUE THREAD

**Issue by braniii** [Elinvention/gnome-shell-extension-nasa-apod#11]
I really like this extension. But on some days I prefer the bing wallpaper of the day. My problem is, that for normal Wallpaper I prefer if the whole desktop is covered. For the APOD where the pictures are often portrait it is not a good at all.
Therefore it would be nice if you either hardcode this command

    gsettings set org.gnome.desktop.background picture-options "scaled"

or even insert in the settings a dropdown menu with some of those options:

    none, wallpaper, centered, scaled, stretched, zoom, spanned

**Comment by Elinvention** [comment]
Yes, I was thinking about adding a setting like that. I will add it.

**Comment by braniii** [comment]
Thx a lot! It's a really good extension.

**Comment by braniii** [comment]
I just updated to the new version 12. Setting is nicely implemented, but don't you think the user setting should be stored? Because if you change the setting to 'wallpaper' via terminal, then also inside the APOD setting it will be changed.

**Comment by Elinvention** [comment]
You want to store the setting separately and when the extension changes the wallpaper, set picture-options to that value, right?

**Comment by braniii** [comment]
Yes exactly. Because I use two different providers (APOD and Bing POD) and latter always resets the option to zoom. So it would be nice if APOD could save the value and change it back.
