### ISSUE TITLE
Description unavailable until refresh

### ISSUE THREAD

**Issue by quasipedia** [Elinvention/gnome-shell-extension-nasa-apod#12]
I often work at night and the background get changed without me noticing (the whole screen been taken up by other windows).  When I restart the computer the following day, I notice the new background, but the description is unavailable/grayed out (from the extension menu) until the extension refreshes (so: the picture remains the same, but now the description is available from the menu.

Already mentioned this elsewhere, but I love the extension! :)

**Comment by Elinvention** [comment]
So two issues here:

1. no notifications when new background is downloaded. Are you sure you didn't disable notifications in settings? 

2. Explanation persistency. I already added this feature in 9c4b0d402e2bb0d8fb8d84777cf7f22863aa9629, so it will be in next release.

Thanks.

**Comment by quasipedia** [comment]
Really my only bugger is number 2.  I'm not even sure number 1 is a thing, it could also be that notifications appears when I am AFK and I do not notice.  I'm not sure.  My settings:

- Hide indicator: OFF
- Notification: ON.
- Use transient: CHECK.

...so it could be AFK + transient... but as I said: whatever it is, it does not bother me. :)

**Comment by Elinvention** [comment]
Just wait for the approval of gnome extensions website 😄
