### ISSUE TITLE
extensions.gnome.org not updated to the latest version 14

### ISSUE THREAD

**Issue by xwry** [Elinvention/gnome-shell-extension-nasa-apod#15]
I would like to update to version 14 but in extensions.gnome.org there is still version 13.
How to update/install It manually ?

**Comment by Elinvention** [comment]
Yes, unfortunately version 14 is still unreviewed, they have been a bit slow lately.

You can use git like this (as it's written on README.md):

```
git clone https://github.com/Elinvention/gnome-shell-extension-nasa-apod.git $HOME/.local/share/gnome-shell/extensions/nasa_apod@elinvention.ovh
gnome-shell-extension-tool -e nasa_apod@elinvention.ovh
```

**Comment by xwry** [comment]
Thanks @Elinvention Your solution worked.
