### ISSUE TITLE
Alternative API keys

### ISSUE THREAD

**Issue by ThibaultLemaire** [Elinvention/gnome-shell-extension-nasa-apod#17]
[Sorry not including template as it's not applicable]

Hi, I've been using this (great) extension for some time now, and as mentioned before (#14), I frequently get the request throttling error message.

I went and got my own API key (as suggested by the error message), and it was surprisingly easy, I was amazed. But that involves a user action. Hell I'm a developer and usually not afraid to get my hands dirty in this kind of techy manipulation, and yet it took me a month or so to gather the will to click that link, not knowing what kind of procedure to expect. So I can only imagine how daunting it can feel for people that just want to enjoy the extension.

**So what about having several default API keys? I'd be willing to contribute mine.**

**Comment by ThibaultLemaire** [comment]
I also wanted to mention that the refresh interval after a failed attempt could be randomized so people don't all request again at the same time.

Oh and please tell me I'm right to think that on a successful download, the image doesn't refresh every 5 minutes.

**Comment by ThibaultLemaire** [comment]
Thank you, I was missing this information. Maybe that could be in a wiki by the way? (I mean the default 6h for normal case, 30min for 429, and 60s offline)

Randomizing is only meaningful if there are a large number of requests at the exact same time. We're dealing with a 1h period, in the end chances aren't that high, or to be precise they depend on the number of people using the same key, which in the end won't get fixed by randomizing the wait interval.

I don't see how you could reduce the number of requests? I mean okay caching the description as well could avoid some requests, but how many? Would it really make a difference?

So yeah, imo our best chance to throttle this problem is by sharing the load on multiple keys.

**Comment by ThibaultLemaire** [comment]
But how would we go about it?

- Assign a random default key at install time?
- Switch key on 429?
- Use a random key for every request? (but then how to handle personal keys that people have requested for themselves?)

**Comment by Elinvention** [comment]
I think we can do this:

- If user has its own key, use that key. If we get a 429, warn the user and stop.
- If user has no key, pick one from a list of default keys. If we get a 429, try again with another key. If there are no more keys retry this whole thing again in 30 minutes.

So exactly the same as it is now, but with the additional "pick a random key from a list and if it doesn't work try with another, until there are no more keys".

**Comment by ThibaultLemaire** [comment]
So you mean we start with random key every time? Or do we start with the last key (that worked)?

I've never touched a gnome extension before, but this doesn't seem like a big change, I can try and make a PR, what do you think?

**Comment by Elinvention** [comment]
Well, if you want to do it, I leave this task to you. Because, you know, GNOME 3.28 was very unstable and buggy for me, so I switched to KDE :sweat_smile:. I hope GNOME 3.30 is in better shape!

Unfortunately, gnome extensions are not well documented, so even a small change can be time consuming. However this change shouldn't be difficult to implement. Feel free to ask if you need help.

**Comment by ThibaultLemaire** [comment]
I'll get to it this weekend.
