### ISSUE TITLE
Icon Color

### ISSUE THREAD

**Issue by codeman6100** [Elinvention/gnome-shell-extension-nasa-apod#2]
It would be nice if the default (or add the option) for the extension icon was white.  All other extensions I use have white or gray-scale icons and the blue NASA icon sticks out.
![screenshot from 2017-05-08 17-18-57](https://cloud.githubusercontent.com/assets/7398125/25825846/8b1ee564-3412-11e7-8d78-0cb62aee835d.png)

**Comment by Elinvention** [comment]
What do you think of the new icon? https://github.com/Elinvention/gnome-shell-extension-nasa-apod/blob/master/icons/saturn.svg

**Comment by codeman6100** [comment]
Looks great.
