### ISSUE TITLE
No tray icons on F30

### ISSUE THREAD

**Issue by Willtech** [Elinvention/gnome-shell-extension-nasa-apod#24]
- Fedora 30
 - GNOME Shell 3.32.1
 - Install via Gnome Software
 - Tray with topicons-plus from Gnome Software
 - Worked correctly with Fedora 29
 - With Fedora 30 no tray icon.
 - Other tray icons work correctly that I have tested.

**Comment by josh1dev** [comment]
Same, the issue is due to GNOME 3.32, not sure if dev is going to fix this tho. Unfortunately I don't have time to figure this out but maybe I can be able to get to it.

**Comment by Elinvention** [comment]
Duplicate of #22
