### ISSUE TITLE
History tab looks weird

### ISSUE THREAD

**Issue by szatan667** [Elinvention/gnome-shell-extension-nasa-apod#25]
Ok so I think history tab looks kind of weird. 
1. Latest (today's) image is not the first or the last one.  It is surrounded by other images. Not sure how (and if) you sort this list byt would be nice to have it sorted by image date.
2. History will load only a couple of extra (historical) images, and that's it. Scrolling down, and up, nothing happens.

PS. Great app anyway. I have created a shell script sometime ago the simply set the paper everytime you login, but this app is something I've been looking for :1st_place_medal: 

- Operating system with version - Ubu 18.04
- GNOME version - 3.28.4
- Installation method - Ubu app store
- Logs 
#7 0x7ffed3755e90 b   resource:///org/gnome/shell/ui/tweener.js:244 (0x7fe5180cf808 @ 159)
#8 0x7ffed3755ef0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe5180b5de0 @ 71)
#9 0x7ffed3755f90 b   resource:///org/gnome/shell/ui/tweener.js:219 (0x7fe5180cf780 @ 15)
g_object_run_dispose: assertion 'G_IS_OBJECT (object)' failed
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x240002c (NASA APOD )
NASA APOD extension: Background thor_LHORHGOBO_final.jpg pinned
NASA APOD extension: Background solargraphBelgrado.jpg pinned
NASA APOD extension: Background thor_LHORHGOBO_final.jpg pinned
NASA APOD extension: Background solargraphBelgrado.jpg pinned
NASA APOD extension: Background thor_LHORHGOBO_final.jpg pinned
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x240eba3 (NASA APOD )
STACK_OP_RAISE_ABOVE: window 0x240eba3 not in stack
STACK_OP_RAISE_ABOVE: window 0x240eba3 not in stack
NASA APOD extension: Background thor_LHORHGOBO_final.jpg pinned
NASA APOD extension: Background unpinned
NASA APOD extension: Background solargraphBelgrado.jpg pinned
NASA APOD extension: Background unpinned
NASA APOD extension: Background rolando-ligustri-C2018Y1_190227_FB_1551288721.jpg pinned
NASA APOD extension: Background unpinned
NASA APOD extension: Background pia23346-16.jpg pinned
NASA APOD extension: Background unpinned
NASA APOD extension: Background 20181013VDB9kerschhuber.jpg pinned
NASA APOD extension: Background unpinned
NASA APOD extension: Background 2019-08-08-JMT19_1521-Pano-Edit.jpg pinned
NASA APOD extension: Background unpinned

**Comment by Elinvention** [comment]
1. The list should be sorted by filename and so the first should be the most recent. As you can see from https://github.com/Elinvention/gnome-shell-extension-nasa-apod/blob/3baab057c6a84914004e2e5a2c3549494cefc0bf/utils.js#L64 Could you list the content of your `~/.cache/apod/` directory?
2. That's because the history tab can display only the images that were downloaded in the past. I could implement a button to download n older images.

**Comment by szatan667** [comment]
OK that makes sense. I thought that the history will always show images from a couple of days back. My download folder had some previous images from different source of apod images. Couldn't find the cache dir you mentioned - it's simply not there. But nevermind that, no issue here, closing the case.

**Comment by Elinvention** [comment]
Perhaps you used a different download folder in the settings?
