### ISSUE TITLE
Won't update past a certain date

### ISSUE THREAD

**Issue by FreedomFaighter** [Elinvention/gnome-shell-extension-nasa-apod#27]
OS: Gentoo/Kernel 5.3.2-x86_64
Gnome Version: GNOME Shell 3.30.2
Installation Method: https
Not sure how to get the logs but last error reported was 500.

I'm attempting to use your api keys and my personal api key.

**Comment by Elinvention** [comment]
Without logs it's difficult to say, but error 500 might indicate a server side issue. 
Without systemd I don't know where they put logs, probably in some file in your home directory. You can always grep your whole home directory: `grep -Ir NASA` (might take some time).

**Comment by Elinvention** [comment]
Now that I'm reading it again, maybe it's the same as #28.

I'm closing this, but feel free to reopen if it's something else.
