### ISSUE TITLE
 Cannot refresh (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by vav4eg** [Elinvention/gnome-shell-extension-nasa-apod#31]
Good day! First of all, I want to thank you for your development. I really like your extension!
I installed the Ubuntu 20.04 LTS system and your extension, but my screen does not update. Please tell me how to fix this.

**journalctl -o cat -f /usr/bin/gnome-shell**
```
NASA APOD extension: Next check @ local time 03:34
NASA APOD extension: Refresh done.
NASA APOD extension: https://api.nasa.gov/planetary/apod?api_key=jCUjMOBpL523SxLoi4PogFZ3YsvvFtVNyEvRd0IB
NASA APOD extension: 1983/2000 requests per hour remaining
JS ERROR: Error: Source.notify() has been moved to Source.showNotification()this code will break in the future
notify@resource:///org/gnome/shell/ui/messageTray.js:868:23
notify@/home/vav4eg/.local/share/gnome-shell/extensions/nasa_apod@elinvention.ovh/notifications.js:27:12
_notifyAPIResults@/home/vav4eg/.local/share/gnome-shell/extensions/nasa_apod@elinvention.ovh/extension.js:281:23
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
_refresh/makeRequest</<@/home/vav4eg/.local/share/gnome-shell/extensions/nasa_apod@elinvention.ovh/extension.js:366:34

NASA APOD extension: Next check @ local time 03:34
NASA APOD extension: Refresh done.
```
P.S. I would really like your extension to be in my native language. Is it possible to implement Russian text in the settings? I can take part in the translation of the text

**Comment by vav4eg** [comment]
Sorry, but it seems to have dawned on me. It is not updated, because there is a video file on the site, not a picture file.

**Comment by Elinvention** [comment]
You're welcome. Try tomorrow, if there is an image it should just update fine.
About language, yes it's possible to translate using a tool like Poedit. You can open the template file located at `locale/nasa_apod.pot` and translate each sentence. Then save as `locale/ru/LC_MESSAGES/nasa_apod.po`. Unfortunately the translations do not work in the preferences menu and I asked for help in #30.

**Comment by Elinvention** [comment]
Let me know if it downloaded today's picture.

**Comment by vav4eg** [comment]
yes, everything works. the picture was not updated due to the video file on the site. When a picture appeared on the site, everything was updated
