### ISSUE TITLE
Is not compatible with Gnome 40

### ISSUE THREAD

**Issue by s001911** [Elinvention/gnome-shell-extension-nasa-apod#36]
Receive the following error in Extensions

```
TypeError: Gtk.CssProvider.get_default is not a function

Stack trace:
  init@/home/joshua/.local/share/gnome-shell/extensions/nasa_apod@elinvention.ovh/prefs.js:20:27
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:25
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**To Reproduce**

1. Upgrade to Gnome 40

**Expected behavior**

Extension continues to work.

**Screenshots**

N/A

**Operating system with version**

- Ubuntu 21.04 (Hirsute Hippo) Beta

**GNOME Shell version**

- 40.0

**Installation method**

- https://extensions.gnome.org/extension/1202/nasa-apod/

**Logs**

```
Removing a network device that was not added
Removing a network device that was not added
Removing a network device that was not added
Removing a network device that was not added
Removing a network device that was not added
Removing a network device that was not added
Removing a network device that was not added
Removing a network device that was not added
Removing a network device that was not added
Removing a network device that was not added
```

**Extension's settings**

```
org.gnome.shell.extensions.nasa-apod background-options 'default'
org.gnome.shell.extensions.nasa-apod image-resolution 'hd'
org.gnome.shell.extensions.nasa-apod pinned-background ''
org.gnome.shell.extensions.nasa-apod screensaver-options 'default'
org.gnome.shell.extensions.nasa-apod image-resolution-metered 'lowres'
org.gnome.shell.extensions.nasa-apod refresh-metered false
org.gnome.shell.extensions.nasa-apod notify true
org.gnome.shell.extensions.nasa-apod hide false
org.gnome.shell.extensions.nasa-apod set-background true
org.gnome.shell.extensions.nasa-apod download-folder '/tmp/'
org.gnome.shell.extensions.nasa-apod last-refresh uint64 1617741962320
org.gnome.shell.extensions.nasa-apod api-keys ['XKSoS8Bv05ij8JH8UWa7eqMavXgGfFStcc6Pu3KH', 'jCUjMOBpL523SxLoi4PogFZ3YsvvFtVNyEvRd0IB']
org.gnome.shell.extensions.nasa-apod last-json "{\"copyright\":\"Kristine Richer\",\"date\":\"2021-04-06\",\"explanation\":\"Is this just a lonely tree on an empty hill? To start, perhaps, but look beyond.  There, a busy universe may wait to be discovered. First, physically, to the left of the tree, is the planet Mars. The red planet, which is the new home to NASA's Perseverance rover, remains visible this month at sunset above the western horizon. To the tree's right is the Pleiades, a bright cluster of stars dominated by several bright blue stars. The featured picture is a composite of several separate foreground and background images taken within a few hours of each other, early last month, from the same location on Vinegar Hill in Milford, Nova Scotia, Canada. At that time, Mars was passing slowly, night after night, nearly in front of the distant Seven Sisters star cluster. The next time Mars will pass angularly as close to the Pleiades as it did in March will be in 2038.\",\"hdurl\":\"https://apod.nasa.gov/apod/image/2104/MartianSisters_Rose_2000.jpg\",\"media_type\":\"image\",\"service_version\":\"v1\",\"title\":\"Mars and the Pleiades Beyond Vinegar Hill\",\"url\":\"https://apod.nasa.gov/apod/image/2104/MartianSisters_Rose_960.jpg\"}\n"
org.gnome.shell.extensions.nasa-apod transient false
org.gnome.shell.extensions.nasa-apod set-lock-screen true
```

**Comment by Elinvention** [comment]
Yes, since there are many breaking changes in the new GNOME release, the extension has to be ported to GNOME 40. The lack of documentation has prevented me from even trying in the past, but now I found about [gjs.guide](https://gjs.guide/extensions/upgrading/gnome-shell-40.html) and that changes everything.

**Comment by biggus-dickus** [comment]
Funny thing: just adding `40.0` to `shell-version` array in `metadata.json` will make it sorta compatible with new Gnome. Settings won't still work, but at least I won't have to stare at the blank background anymore.

Just don't forget to restart Gnome shell or re-login after you modify that file.

**Comment by Elinvention** [comment]
I uploaded a new version on extensions.gnome.org. The main functionality is ok. I started porting the settings to GTK4 and half of it is broken, but better than nothing.

**Comment by lunaryorn** [comment]
@Elinvention Would you make a tag for the new release?  I maintain an Arch Linux package for this extension, and I'd need a tag to build from 🙂

**Comment by Elinvention** [comment]
The tag is already here (I just have to copy that info into github's releases to enable pretty print) https://github.com/Elinvention/gnome-shell-extension-nasa-apod/releases/tag/22

**Comment by lunaryorn** [comment]
@Elinvention Ah, sorry; I just looked at releases :pensive: 

Thanks for your work on this extension :heart:

**Comment by lunaryorn** [comment]
@Elinvention I just noticed that the makefile refers to a non-existing `theme.css` now.

**Comment by Elinvention** [comment]
@lunaryorn yes, you are right, I renamed it, but I forgot to update the Makefile. Thanks for noticing this.

**Comment by Elinvention** [comment]
I released a new version (23) that should be fully working on GNOME 40. I will close this when it's approved on extensions.gnome.org.

**Comment by s001911** [comment]
I have just install this from extensions and confirmed it's working on my setup

**Comment by Elinvention** [comment]
@s001911 thanks for reporting back.

**Comment by lunaryorn** [comment]
@Elinvention The tag v23 isn't on "main"; did you perhaps only push the tag but not the main branch?

**Comment by lunaryorn** [comment]
I'm sorry, I wasn't precise: I am aware that the tag exists, and I do know that it's not prefixed with `v`.  In fact there's no issue with the tag.

However, the commit behind the tag is _not_ on `main`; according to Github the tip of that branch is an older commit:

![image](https://user-images.githubusercontent.com/224922/115007668-85b82980-9eaa-11eb-9d1e-7d604877a525.png)

Navigating to the tagged commit through Github also shows a warning that the commit is not on any branch:

![image](https://user-images.githubusercontent.com/224922/115007933-d3cd2d00-9eaa-11eb-8080-aab8cb229065.png)

It looks as if you pushed the tag but not the branch.

**Comment by Elinvention** [comment]
I thought that `git push --tags` was enough. Now it should be fine.
