### ISSUE TITLE
different aspect ratio wallpapers

### ISSUE THREAD

**Issue by pvmm** [Elinvention/gnome-shell-extension-nasa-apod#37]
Wallpaper should cover the whole screen, even if it has a different aspect ratio. APOD could upscale it if necessary and crop the result. Today's wallpaper (2021-04-13) is an example of this issue.

**Comment by Elinvention** [comment]
Have you tried changing how the background is shown in the preferences? The problem with stretching images with a very different aspect ratio is that they will look too distorted.

**Comment by pvmm** [comment]
Maintain the aspect ratio by magnify both width and height by same amount until they are big enough to cover the whole screen.

**Comment by Elinvention** [comment]
That's what gnome can already do for you. Look at the extension preferences or use gnome-tweaks.
