### ISSUE TITLE
Font rendering in settings dialog broken

### ISSUE THREAD

**Issue by lunaryorn** [Elinvention/gnome-shell-extension-nasa-apod#38]
**Describe the bug**

Since version 23 font rendering in the settings dialog is noticeably different from other apps.  See the following screenshot which shows the description popup, Gnome Tweaks and the settings dialog of this extension (I think you need to view it at its original size to see the issue):

![image](https://user-images.githubusercontent.com/224922/114852397-06135780-9de3-11eb-9661-11e4f0507fd8.png)

As you can see fonts in the settings dialog look really different, and also really bad. It looks as hinting stopped working. 

**To Reproduce**

I do not know how to reproduce this behaviour; it's perhaps related to my font configuration (though I don't have any unusual font configuration as far as I am aware)

**Expected behavior**

Fonts in the settings dialog should look like fonts elsewhere.

**Screenshots**

See above.

**Operating system with version**
For example: Arch Linux.

**GNOME Shell version**

```
$ gnome-shell --version
GNOME Shell 40.0
```

**Installation method**
- [AUR](https://aur.archlinux.org/packages/gnome-shell-extension-nasa-apod/)

**Logs <- VERY IMPORTANT**

No extra logs appear when opening the extension dialog.

**Comment by Elinvention** [comment]
All I can say right now is that it doesn't happen on my machine. :thinking: If I open gnome tweaks I can change hinting and anti-aliasing and see the difference live.

**Comment by lunaryorn** [comment]
Looks like Gtk 4 has a few issues with font rendering because it was apparently "improved" (sorry for the sarcasm :pensive: )

I've made a few changes to my font config and picked a different font and now it looks kinda okay in Gtk 3 and Gtk 4, so we can close this.

I'm sorry for the noise, ought to have googled first :pensive:
