### ISSUE TITLE
API keys - "Add" button broken

### ISSUE THREAD

**Issue by rorymobley** [Elinvention/gnome-shell-extension-nasa-apod#43]
the popup is a mal-formed window with no text box to input anything and even the buttons just say "gtk-cancel" or "gtk-okay", without bothering to turn it into English. Version 30 that I just downloaded from gnome's extension site.
![Screenshot from 2021-11-07 17-42-19](https://user-images.githubusercontent.com/212093/140666321-95b469ab-8c2d-42bd-97bb-116b911bc393.png)

**Comment by Elinvention** [comment]
I forgot about that. Thanks for reporting!
