### ISSUE TITLE
only light mode wallpaper is updated in Gnome 42

### ISSUE THREAD

**Issue by g-voelker** [Elinvention/gnome-shell-extension-nasa-apod#48]
At the moment only the light mode wallpaper is updated. The dark mode stays untouched. In general it would be nice to either have both wallpapers updated or to have an option to choose which ones are to be updated by the extension.

**Comment by amfern** [comment]
noticed the same behavior, wallpapers doesn't change in dark mode

**Comment by Kirottu** [comment]
I can also confirm this.

**Comment by amfern** [comment]
Can confirm, this issue is fixed, thank you, @Elinvention
