### ISSUE TITLE
Compatibility with Gnome 43

### ISSUE THREAD

**Issue by captnfab** [Elinvention/gnome-shell-extension-nasa-apod#50]
Gnome 43 is out, and apparently there's some API breakage (`Soup.SessionAsync is not a constructor`)

**Comment by captnfab** [comment]
According to https://lazka.github.io/pgi-docs/Soup-2.4/classes/SessionAsync.html#Soup.SessionAsync `Soups.SessionAsync` is deprecated and to be replaced by `Soup.Session`

**Comment by captnfab** [comment]
It looks like soup3 is used now instead of soup 2.4.
The other problematic constructor is https://lazka.github.io/pgi-docs/Soup-2.4/classes/ProxyResolverDefault.html which doesn't exist anymore.
However, default behavior for proxy seems to be sane and the configuration line should be removable safely: https://libsoup.org/libsoup-3.0/property.Session.proxy-resolver.html

That said, I tried replacing SessionAsync with Session and removing ProxyResolverDefault lines, and the extension is unable to perform a refresh. So, more brain juice is needed…

**Comment by Elinvention** [comment]
Thanks for looking into this. I found this guide https://libsoup.org/libsoup-2.4/libsoup-session-porting.html that may help.

**Comment by Elinvention** [comment]
I fixed the extension and released version 34 on GitHub and on extensions.gnome.org. You should receive the update automatically as soon as the review process is complete.
Thanks for your interest in this extension.

**Comment by Ahmard** [comment]
> I fixed the extension and released version 34 on GitHub and on extensions.gnome.org. You should receive the update automatically as soon as the review process is complete.
> Thanks for your interest in this extension.

This is awesome.
Thank you.
