### ISSUE TITLE
Downloaded image too large for monitor

### ISSUE THREAD

**Issue by volga45** [Elinvention/gnome-shell-extension-nasa-apod#57]
The downloaded image is too large for my monitor, in other words it it can be seen thru the top bar in Ubuntu which displays the power/log off button. 

I executed: 
$ xrandr | grep ' connected'
got:
XWAYLAND0 connected primary 3840x1600+0+0 (normal left inverted right x axis y axis) 880mm x 370mm

My monitor is a LG widescreen Model # 38GN950 (if that helps).

I am new to Ubuntu/Linux so please excuse me if the answer is self evident.

I have searched looking for a way to modify the display sizeand  was unable to find it.

I am using Ubuntu 22.04.2 LTS

**GNOME Shell version**
$ gnome-shell --version
GNOME Shell 42.5

**Installation method**
- https://extensions.gnome.org/extension/1202/nasa-apod/

**Logs <- VERY IMPORTANT**

Please paste below the relevant parts of `journalctl -f -o cat /usr/bin/gnome-shell`.
$ journalctl -f -o cat /usr/bin/gnome-shell
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
DING: Detected async api for thumbnails
DING: GNOME nautilus 42.2
NASA APOD extension: https://api.nasa.gov/planetary/apod?api_key=XKSoS8Bv05ij8JH8UWa7eqMavXgGfFStcc6Pu3KH
NASA APOD extension: 1999/2000 requests per hour remaining
NASA APOD extension: Downloading https://apod.nasa.gov/apod/image/2305/M101Sn_Stocks_after_2560.jpg to file:///home/john/.cache/apod/2023-05-22-Supernova%20Discovered%20in%20Nearby%20Spiral%20Galaxy%20M101.jpg
NASA APOD extension: Download size: 574451B
NASA APOD extension: Download successful
NASA APOD extension: Next check @ local time 05:18
NASA APOD extension: Refresh done.

```

**Extension's settings**

$ gsettings --schemadir ~/.local/share/gnome-shell/extensions/nasa_apod@elinvention.ovh/schemas/ list-recursively org.gnome.shell.extensions.nasa-apod
org.gnome.shell.extensions.nasa-apod api-keys ['XKSoS8Bv05ij8JH8UWa7eqMavXgGfFStcc6Pu3KH', 'jCUjMOBpL523SxLoi4PogFZ3YsvvFtVNyEvRd0IB']
org.gnome.shell.extensions.nasa-apod background-options 'default'
org.gnome.shell.extensions.nasa-apod download-folder ''
org.gnome.shell.extensions.nasa-apod hide false
org.gnome.shell.extensions.nasa-apod image-resolution 'hd'
org.gnome.shell.extensions.nasa-apod image-resolution-metered 'lowres'
org.gnome.shell.extensions.nasa-apod last-json "{\"copyright\":\"Craig Stocks\",\"date\":\"2023-05-22\",\"explanation\":\"A nearby star has exploded and humanity's telescopes are turning to monitor it.  The supernova, dubbed SN 2023ifx, was discovered by Japanese astronomer Koichi Itagaki three days ago and subsequently located on automated images from the Zwicky Transient Facility two days earlier.  SN 2023ifx occurred in the photogenic Pinwheel Galaxy M101, which, being only about 21 million light years away, makes it the closest supernova seen in the past five years, the second closest in the past 10 years, and the second supernova found in M101 in the past 15 years.  Rapid follow up observations already indicate that SN 2023ifx is a Type II supernova, an explosion that occurs after a massive star runs out of nuclear fuel and collapses.  The featured image shows home spiral galaxy two days ago with the supernova highlighted, while the roll-over image shows the same galaxy a month before. SN 2023ifx will likely brighten and remain visible to telescopes for months.  Studying such a close and young Type II supernova may yield new clues about massive stars and how they explode.\",\"hdurl\":\"https://apod.nasa.gov/apod/image/2305/M101Sn_Stocks_after_2560.jpg\",\"media_type\":\"image\",\"service_version\":\"v1\",\"title\":\"Supernova Discovered in Nearby Spiral Galaxy M101\",\"url\":\"https://apod.nasa.gov/apod/image/2305/M101Sn_Stocks_after_960.jpg\"}\n"
org.gnome.shell.extensions.nasa-apod last-refresh uint64 1684729109446
org.gnome.shell.extensions.nasa-apod notify true
org.gnome.shell.extensions.nasa-apod pinned-background ''
org.gnome.shell.extensions.nasa-apod refresh-metered false
org.gnome.shell.extensions.nasa-apod set-background true
org.gnome.shell.extensions.nasa-apod transient true

Any help is most appreciated.

**Comment by Elinvention** [comment]
Thanks for filling out the form, but I'm not sure if I understand you correctly.

You can change how the background image is displayed in the extension's settings. Most images from APOD will not fit monitors perfectly most of the time, because they are usually square or too small, so you have to find the compromise that you like most.

However when you say "it can be seen thru the top bar in Ubuntu", maybe there is some kind of transparency in the top bar? Sorry, I haven't been an Ubuntu user for many years, but there is surely a way to change that.

If I missed the point send me a screenshot.

**Comment by Elinvention** [comment]
Stale
