### ISSUE TITLE
Http Status Code 502 Error

### ISSUE THREAD

**Issue by mushaibkhan** [Elinvention/gnome-shell-extension-nasa-apod#58]
Error updating wallpaper  i even tried re-installing extension 
![Screenshot from 2023-06-07 16-04-42](https://github.com/Elinvention/gnome-shell-extension-nasa-apod/assets/61492565/1005bc2e-e54c-4803-a347-a14ac6fe269a)

**Comment by S0litaire** [comment]
Getting an API error as well. 
Even a new API code from the api.nasa.gov site is not accepted.

**Comment by maplebar** [comment]
Here's is the related issue on the NASA apod-api project.

https://github.com/nasa/apod-api/issues/108

**Comment by mushaibkhan** [comment]
Fixed Now
