### ISSUE TITLE
Media Type Unsupported

### ISSUE THREAD

**Issue by flycal6** [Elinvention/gnome-shell-extension-nasa-apod#6]
Each day give the message "Media Type Video Unsupported", but the APOD is not a video, just a regular image.
This is on Gnome Wayland 3.24

**Comment by flycal6** [comment]
It started working on the second day.  Could've been the time difference.  I'm UTC +3.

**Comment by Elinvention** [comment]
However I suggest you to update your extension (you can do that from extensions.gnome.org). The behavior when there is something different from an image has not changed though.

**Comment by Roman-Kirnos** [comment]
Hello! Can you help me? I receive massage "Media Type Video Unsupported", when it is video, but why? Maybe I have to install something?

**Comment by Elinvention** [comment]
Simply because videos can't be used as a wallpaper on GNOME.
