### ISSUE TITLE
issues with images with forward slash "/" in the title

### ISSUE THREAD

**Issue by S0litaire** [Elinvention/gnome-shell-extension-nasa-apod#60]
Issue:  in today's APOD the jpeg's title included a forward slash, throwing up a 200 error and the image is not displayed.

Error : 
```
NASA APOD extention error : Genric error
Gio.IOErrorEnum: Error removing file /home/bill/Pictures/APOD/2023-07-14-Comet C/2023 E1 ATLAS near Perihelion.jpg No such file or directory
```
![image](https://github.com/Elinvention/gnome-shell-extension-nasa-apod/assets/1823781/cf8678a0-8ad4-42e7-a90a-9a2fb148d0f9)

The Image it's trying to save as:
2023-07-14-Comet C/2023 E1 ATLAS near Perihelion.jpg
So it's looking for a folder called "2003-07-14-Comet C" to save the image into:

Workaround: 
I created a folder called "2003-07-14-Comet C" and the image saved and displayed correctly.

direct NASA link to image:
https://apod.nasa.gov/apod/image/2307/C_2023_E1_ATLAS_C14F2_DEBartlett1024.jpg
NASA Title: 
 Comet C/2023 E1 ATLAS near Perihelion 
 
 Solution:
 When creating locally saved image replace "/" with "-" or remove completely

**Comment by Elinvention** [comment]
Should be solved with version 37. Feel free to reopen if it is not.
