### ISSUE TITLE
Colon in file name generate issues when opening the file with Windows

### ISSUE THREAD

**Issue by Prodeguerriero** [Elinvention/gnome-shell-extension-nasa-apod#63]
**Describe the bug**

Some files happen to have a _colon_ ":" in their name. This is fine on Linux, less so on Windows. I notice because I have a backup routine running when I boot into windows to back up the folder where I store my wallpapers.
Windows does not know how to handle the file and, therefore, starts acting up

**To Reproduce**

1. Let the extension download wallpapers until it downloads one that has a colon in the file name (Latest is from 2023-11-27).  
   Or manually rename a file on Linux, adding a colon.
2. Boot into Windows and try to interact with the file

**Expected behavior**

The file names should avoid any known problematic characters. It would be handy to have the extension check the string of the file name and maybe replace the "nasty" characters.
I tried to take a look at the code to make a pull request, but I am in over my head.

**Screenshots**

None for now

**Operating system with version**

The extension is running on Ubuntu 22.04 LTS. The Windows version having issues is Windows 10

**GNOME Shell version**

42.9

**Installation method**
- https://extensions.gnome.org/extension/1202/nasa-apod/

**Logs <- VERY IMPORTANT**

Not relevant

**Extension's settings**

Also not relevant

**Comment by Prodeguerriero** [comment]
Grazie mille @Elinvention :)

**Comment by Elinvention** [comment]
Di niente. Grazie per la segnalazione!

**Comment by Prodeguerriero** [comment]
> I think there is a way to force the update on extensions.gnome.org, however the newer versions won't work at all because GNOME 45 changed a lot of things under the hood, making it incompatible with previous versions. I had to change a lot of things to make this extension work again on GNOME 45.

Never mind then. I'll stick to my current version for now. I am now dealing with a different problem. I am not getting new wallpapers since December 4. If I can't fix it, I'll open a new issue.

Thanks again
