### ISSUE TITLE
doesn't work in gnome 3.26 (alpha)

### ISSUE THREAD

**Issue by mpkh** [Elinvention/gnome-shell-extension-nasa-apod#9]

**Comment by Elinvention** [comment]
Did you modify metadata.json? You have to add your gnome shell's version.

**Comment by mpkh** [comment]
no...

**Comment by Elinvention** [comment]
I will add 3.26 to metadata.json when I get a chance to test it or if someone tells me that it works. Thanks.

**Comment by mpkh** [comment]
@Elinvention it's not about metadata, it works fine with old metadata but plugin can't change the wallpaper anymore, it displays info but just removes old wallpaper without setting new one

**Comment by Elinvention** [comment]
Ok, I need more information.

- run `journalctl -f -o cat /usr/bin/gnome-shell` then click on refresh in the extension's menu, when it completes send me the output (I just need the lines that begin with NASA APOD extension)
- have a look in `~/.cache/apod/`, if you haven't changed download folder in the settings. Check that there are images, and that they can be opened.

**Comment by Elinvention** [comment]
I found out that the extension doesn't work out of the box. It's not GNOME 3.26's fault. You have to set the download folder in the settings at least once, otherwise it sets a wrong path as wallpaper.

Thank you for reporting this issue.
